MvcCoreLinqToSql/Models/Empleado.cs
namespace MvcCoreLinqToSql.Models
{
    public class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Apellido { get; set; }
        public string Oficio { get; set; }
        public int Salario { get; set; }
        public int IdDepartamento { get; set; }
    }
}

MvcCoreLinqToSql/Models/Enfermo.cs
namespace MvcCoreLinqToSql.Models
{
    public class Enfermo
    {
        public string Inscripcion { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string NumeroSeguridadSocial { get; set; }
    }
}

MvcCoreLinqToSql/Models/ErrorViewModel.cs
namespace MvcCoreLinqToSql.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreLinqToSql/Models/ResumenEmpleados.cs
namespace MvcCoreLinqToSql.Models
{
    public class ResumenEmpleados
    {
        public int Personas { get; set; }
        public int MaxSalario { get; set; }
        public double MediaSalarial { get; set; }
        public List<Empleado> Empleados { get; set; }
    }
}

MvcCoreLinqToSql/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToSql.Models;
using MvcCoreLinqToSql.Repositories;

namespace MvcCoreLinqToSql.Controllers
{
    public class EmpleadosController : Controller
    {
        private RepositoryEmpleados repo;

        public EmpleadosController()
        {
            this.repo = new RepositoryEmpleados();
        }

        public IActionResult Index()
        {
            List<Empleado> empleados = this.repo.GetEmpleados();
            return View(empleados);
        }

        public IActionResult Details(int id)
        {
            Empleado emp = this.repo.FindEmpleado(id);
            return View(emp);
        }

        public IActionResult BuscadorEmpleados()
        {
            return View();
        }

        [HttpPost]
        public IActionResult BuscadorEmpleados(string oficio, int salario)
        {
            List<Empleado> empleados = this.repo.GetEmpleadosOficioSalario(oficio, salario);
            if(empleados == null)
            {
                ViewData["MENSAJE"] = "No se han encontrado empleados";
                return View();
            }
            else
            {
                return View(empleados);
            }
        }

        public IActionResult DatosEmpleados()
        {
            List<string> oficios = this.repo.GetOficios();
            ViewData["OFICIOS"] = oficios;
            return View();
        }

        [HttpPost]
        public IActionResult DatosEmpleados(string oficio)
        {
            ResumenEmpleados model = this.repo.GetEmpleadosOficio(oficio);
            List<string> oficios = this.repo.GetOficios();
            ViewData["OFICIOS"] = oficios;
            return View(model);
        }

    }
}

MvcCoreLinqToSql/Controllers/EnfermosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToSql.Models;
using MvcCoreLinqToSql.Repositories;

namespace MvcCoreLinqToSql.Controllers
{
    public class EnfermosController : Controller
    {
        RepositoryEnfermos repo;

        public EnfermosController()
        {
            this.repo = new RepositoryEnfermos();
        }

        public IActionResult Index()
        {
            List<Enfermo> enfermos = this.repo.GetEnfermos();
            return View(enfermos);
        }

        public IActionResult Details(string id)
        {
            Enfermo enf = this.repo.FindEnfermo(id);
            return View(enf);
        }

        public IActionResult Delete(string id)
        {
            this.repo.DeleteEnfermo(id);
            return RedirectToAction("Index");
        }

    }
}

MvcCoreLinqToSql/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToSql.Models;

namespace MvcCoreLinqToSql.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreLinqToSql/Views/Empleados/BuscadorEmpleados.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Empleado>

<h1>Buscador empleados</h1>
<form method="POST">
    <label>Introduzca oficio: </label>
    <input type="text" name="oficio" class="form-control"/>
    <label>Introduzca salario: </label>
    <input type="number" name="salario" class="form-control" />
    <button class="btn btn-info">Buscar empleados</button>
</form>

<h3 style="color: rebeccapurple">
    @ViewData["MENSAJE"]
</h3>

@if(Model != null)
{
    <table class="table table-info table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>APELLIDO</th>
                <th>OFICIO</th>
                <th>SALARIO</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Empleado empleado in Model)
            {
                <tr>
                    <td>@empleado.IdEmpleado</td>
                    <td>@empleado.Apellido</td>
                    <td>@empleado.Oficio</td>
                    <td>@empleado.Salario</td>
                </tr>
            }
        </tbody>
    </table>
}

MvcCoreLinqToSql/Views/Empleados/DatosEmpleados.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model ResumenEmpleados

<h1>Lambda Linq Empleados</h1>

<form method="POST">
    <label>Oficio: </label>
    <select name="oficio" class="form-control">
        @foreach(string oficio in ViewData["OFICIOS"] as List<string>)
            {
                <option>@oficio</option>   
            }
    </select>
    <button class="btn btn-warning">Buscar empleados</button>
</form>

@if(Model != null)
{
    <ul class="list-group">
        <li class="list-group-item list-group-item-secondary">
            Personas: @Model.Personas
        </li>
        <li class="list-group-item list-group-item-secondary">
            Maximo salario: @Model.MaxSalario
        </li>
        <li class="list-group-item list-group-item-secondary">
            Media salarial: @Model.MediaSalarial
        </li>
    </ul>
    @if(Model.Empleados != null)
    {
        <table class="table table-bordered table-warning">
            <thead>
                <tr>
                    <th>Apellido</th>
                    <th>Oficio</th>
                    <th>Salario</th>
                    <th>Departamento</th>
                </tr>
            </thead>
            <tbody>
                @foreach(Empleado empleado in Model.Empleados)
                {
                    <tr>
                        <td>@empleado.Apellido</td>
                        <td>@empleado.Oficio</td>
                        <td>@empleado.Salario</td>
                        <td>@empleado.IdDepartamento</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h3 style="color:rebeccapurple">No existen empleados</h3>
    }
} 

MvcCoreLinqToSql/Views/Empleados/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Empleado

<h1 style="color: blue">Details</h1>

<a asp-controller="Empleados" asp-action="Index">Back to list</a>

<ul class="list-group">
    <li class="list-group-item">
        Id: @Model.IdEmpleado
    </li>
    <li class="list-group-item">
        Apellido: @Model.Apellido
    </li>
    <li class="list-group-item">
        Oficio: @Model.Oficio
    </li>
    <li class="list-group-item">
        Salario: @Model.Salario
    </li>
    <li class="list-group-item">
        Departamento: @Model.IdDepartamento
    </li>
</ul>

MvcCoreLinqToSql/Views/Empleados/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Empleado>

<h1>Empleados Linq To Sql</h1>

<table class="table table-info table-bordered">
    <thead>
        <tr>
            <th>APELLIDO</th>
            <th>OFICIO</th>
            <th>SALARIO</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach(Empleado empleado in Model)
        {
            <tr>
                <td>@empleado.Apellido</td>
                <td>@empleado.Oficio</td>
                <td>@empleado.Salario</td>
                <td>
                    <a asp-controller="Empleados" asp-action="Details" asp-route-id="@empleado.IdEmpleado">Details</a>
                </td>
            </tr>         
        }
    </tbody>
</table>

MvcCoreLinqToSql/Views/Enfermos/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Enfermo

<a asp-controller="Enfermos" asp-action="Index">Back to List</a>

<h1>Details Enfermo</h1>
<ul class="list-group">
    <li class="list-group-item">
        Inscripcion: @Model.Inscripcion
    </li>
    <li class="list-group-item">
        Apellido: @Model.Apellido
    </li>
    <li class="list-group-item">
        Direccion: @Model.Direccion
    </li>
    <li class="list-group-item">
        Fecha nacimiento: @Model.FechaNacimiento
    </li>
    <li class="list-group-item">
        Sexo: @Model.Sexo
    </li>
    <li class="list-group-item">
        Numero seguridad social: @Model.NumeroSeguridadSocial
    </li>
</ul>

MvcCoreLinqToSql/Views/Enfermos/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Enfermo>

<h1>Enfermos Linq To Sql</h1>

@if(Model != null)
{
    <table>
        <thead>
            <tr>
                <th>APELLIDO</th>
                <th>ACCIONES</th>
            </tr>
        </thead>
        @foreach(Enfermo enfermo in Model)
        {
            <tr>
                <td>@enfermo.Apellido</td>
                <td>
                    <a class="btn btn-dark" asp-controller="Enfermos" asp-action="Details" asp-route-id="@enfermo.Inscripcion">Details</a>
                    <a class ="btn btn-danger" asp-controller="Enfermos" asp-action="Delete" asp-route-id="@enfermo.Inscripcion">Delete</a>
                </td>
            </tr>
        }
    </table>
}

MvcCoreLinqToSql/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreLinqToSql/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreLinqToSql</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreLinqToSql.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreLinqToSql</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="Index">Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="DatosEmpleados">Datos Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="BuscadorEmpleados">Buscador empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enfermos" asp-action="Index">Enfermos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - MvcCoreLinqToSql - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>